TEMPLATES = {
    "gameplay_split": {
        "id": "gameplay_split",
        "name": "Gameplay Split",
        "description": "Your video on top, gameplay on bottom. Most viral format.",
        "layout": "gameplay_split",
        "default_bg_category": "gameplay",
        "default_split_ratio": 0.55,
    },
    "satisfying_split": {
        "id": "satisfying_split",
        "name": "Satisfying Split",
        "description": "Your video on top, satisfying ASMR clip on bottom.",
        "layout": "satisfying_split",
        "default_bg_category": "satisfying",
        "default_split_ratio": 0.55,
    },
    "side_by_side": {
        "id": "side_by_side",
        "name": "Side by Side",
        "description": "Your video on the left, background clip on the right.",
        "layout": "side_by_side",
        "default_split_ratio": 0.5,
    },
    "picture_in_picture": {
        "id": "picture_in_picture",
        "name": "Picture in Picture",
        "description": "Background fullscreen, your video as small corner overlay.",
        "layout": "picture_in_picture",
        "pip_scale": 0.30,
        "pip_position": "bottom_right",
    },
    "caption_bar": {
        "id": "caption_bar",
        "name": "Caption Bar",
        "description": "Your video on top 70%, clean caption space on bottom.",
        "layout": "caption_bar",
        "bar_color": "black",
    },
}
